version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/node"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/node-proto"
    schedule:
      interval: "weekly"
