// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.13.0
// source: stroeer/coremedia/v1/curation_service.proto

package coremedia

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetCuratedStageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageId string `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
}

func (x *GetCuratedStageRequest) Reset() {
	*x = GetCuratedStageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_coremedia_v1_curation_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCuratedStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCuratedStageRequest) ProtoMessage() {}

func (x *GetCuratedStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_coremedia_v1_curation_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCuratedStageRequest.ProtoReflect.Descriptor instead.
func (*GetCuratedStageRequest) Descriptor() ([]byte, []int) {
	return file_stroeer_coremedia_v1_curation_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCuratedStageRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

type GetCuratedStageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage *CuratedStage `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
}

func (x *GetCuratedStageResponse) Reset() {
	*x = GetCuratedStageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_coremedia_v1_curation_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCuratedStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCuratedStageResponse) ProtoMessage() {}

func (x *GetCuratedStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_coremedia_v1_curation_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCuratedStageResponse.ProtoReflect.Descriptor instead.
func (*GetCuratedStageResponse) Descriptor() ([]byte, []int) {
	return file_stroeer_coremedia_v1_curation_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCuratedStageResponse) GetStage() *CuratedStage {
	if x != nil {
		return x.Stage
	}
	return nil
}

type GetCuratedStagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageIds []string `protobuf:"bytes,1,rep,name=stage_ids,json=stageIds,proto3" json:"stage_ids,omitempty"`
}

func (x *GetCuratedStagesRequest) Reset() {
	*x = GetCuratedStagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_coremedia_v1_curation_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCuratedStagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCuratedStagesRequest) ProtoMessage() {}

func (x *GetCuratedStagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_coremedia_v1_curation_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCuratedStagesRequest.ProtoReflect.Descriptor instead.
func (*GetCuratedStagesRequest) Descriptor() ([]byte, []int) {
	return file_stroeer_coremedia_v1_curation_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetCuratedStagesRequest) GetStageIds() []string {
	if x != nil {
		return x.StageIds
	}
	return nil
}

type GetCuratedStagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stages []*CuratedStage `protobuf:"bytes,1,rep,name=stages,proto3" json:"stages,omitempty"`
}

func (x *GetCuratedStagesResponse) Reset() {
	*x = GetCuratedStagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stroeer_coremedia_v1_curation_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCuratedStagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCuratedStagesResponse) ProtoMessage() {}

func (x *GetCuratedStagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stroeer_coremedia_v1_curation_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCuratedStagesResponse.ProtoReflect.Descriptor instead.
func (*GetCuratedStagesResponse) Descriptor() ([]byte, []int) {
	return file_stroeer_coremedia_v1_curation_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCuratedStagesResponse) GetStages() []*CuratedStage {
	if x != nil {
		return x.Stages
	}
	return nil
}

var File_stroeer_coremedia_v1_curation_service_proto protoreflect.FileDescriptor

var file_stroeer_coremedia_v1_curation_service_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x73,
	0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x2e, 0x76, 0x31, 0x1a, 0x28, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x75, 0x72, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x22, 0x53, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73,
	0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x75, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x22, 0x36, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x75,
	0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x73, 0x22,
	0x56, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x74,
	0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x75, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x67, 0x65, 0x73, 0x32, 0xf8, 0x01, 0x0a, 0x0f, 0x43, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x70, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x43, 0x75, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x2c,
	0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x73,
	0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x73, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x2d, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2e, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x61, 0x74,
	0x65, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x57, 0x0a, 0x17, 0x64, 0x65, 0x2e, 0x73, 0x74, 0x72, 0x6f, 0x65, 0x65, 0x72,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a,
	0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x6f,
	0x65, 0x65, 0x72, 0x2f, 0x74, 0x61, 0x70, 0x69, 0x72, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x74, 0x72,
	0x6f, 0x65, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x76,
	0x31, 0x3b, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_stroeer_coremedia_v1_curation_service_proto_rawDescOnce sync.Once
	file_stroeer_coremedia_v1_curation_service_proto_rawDescData = file_stroeer_coremedia_v1_curation_service_proto_rawDesc
)

func file_stroeer_coremedia_v1_curation_service_proto_rawDescGZIP() []byte {
	file_stroeer_coremedia_v1_curation_service_proto_rawDescOnce.Do(func() {
		file_stroeer_coremedia_v1_curation_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_stroeer_coremedia_v1_curation_service_proto_rawDescData)
	})
	return file_stroeer_coremedia_v1_curation_service_proto_rawDescData
}

var file_stroeer_coremedia_v1_curation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stroeer_coremedia_v1_curation_service_proto_goTypes = []interface{}{
	(*GetCuratedStageRequest)(nil),   // 0: stroeer.coremedia.v1.GetCuratedStageRequest
	(*GetCuratedStageResponse)(nil),  // 1: stroeer.coremedia.v1.GetCuratedStageResponse
	(*GetCuratedStagesRequest)(nil),  // 2: stroeer.coremedia.v1.GetCuratedStagesRequest
	(*GetCuratedStagesResponse)(nil), // 3: stroeer.coremedia.v1.GetCuratedStagesResponse
	(*CuratedStage)(nil),             // 4: stroeer.coremedia.v1.CuratedStage
}
var file_stroeer_coremedia_v1_curation_service_proto_depIdxs = []int32{
	4, // 0: stroeer.coremedia.v1.GetCuratedStageResponse.stage:type_name -> stroeer.coremedia.v1.CuratedStage
	4, // 1: stroeer.coremedia.v1.GetCuratedStagesResponse.stages:type_name -> stroeer.coremedia.v1.CuratedStage
	0, // 2: stroeer.coremedia.v1.CurationService.GetCuratedStage:input_type -> stroeer.coremedia.v1.GetCuratedStageRequest
	2, // 3: stroeer.coremedia.v1.CurationService.GetCuratedStages:input_type -> stroeer.coremedia.v1.GetCuratedStagesRequest
	1, // 4: stroeer.coremedia.v1.CurationService.GetCuratedStage:output_type -> stroeer.coremedia.v1.GetCuratedStageResponse
	3, // 5: stroeer.coremedia.v1.CurationService.GetCuratedStages:output_type -> stroeer.coremedia.v1.GetCuratedStagesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stroeer_coremedia_v1_curation_service_proto_init() }
func file_stroeer_coremedia_v1_curation_service_proto_init() {
	if File_stroeer_coremedia_v1_curation_service_proto != nil {
		return
	}
	file_stroeer_coremedia_v1_curated_stage_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_stroeer_coremedia_v1_curation_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCuratedStageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stroeer_coremedia_v1_curation_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCuratedStageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stroeer_coremedia_v1_curation_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCuratedStagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stroeer_coremedia_v1_curation_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCuratedStagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stroeer_coremedia_v1_curation_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stroeer_coremedia_v1_curation_service_proto_goTypes,
		DependencyIndexes: file_stroeer_coremedia_v1_curation_service_proto_depIdxs,
		MessageInfos:      file_stroeer_coremedia_v1_curation_service_proto_msgTypes,
	}.Build()
	File_stroeer_coremedia_v1_curation_service_proto = out.File
	file_stroeer_coremedia_v1_curation_service_proto_rawDesc = nil
	file_stroeer_coremedia_v1_curation_service_proto_goTypes = nil
	file_stroeer_coremedia_v1_curation_service_proto_depIdxs = nil
}
