// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package section

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// WebSectionServiceClient is the client API for WebSectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebSectionServiceClient interface {
	GetWebSectionPage(ctx context.Context, in *GetWebSectionPageRequest, opts ...grpc.CallOption) (*GetWebSectionPageResponse, error)
}

type webSectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebSectionServiceClient(cc grpc.ClientConnInterface) WebSectionServiceClient {
	return &webSectionServiceClient{cc}
}

var webSectionServiceGetWebSectionPageStreamDesc = &grpc.StreamDesc{
	StreamName: "GetWebSectionPage",
}

func (c *webSectionServiceClient) GetWebSectionPage(ctx context.Context, in *GetWebSectionPageRequest, opts ...grpc.CallOption) (*GetWebSectionPageResponse, error) {
	out := new(GetWebSectionPageResponse)
	err := c.cc.Invoke(ctx, "/stroeer.web.section.v1.WebSectionService/GetWebSectionPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebSectionServiceService is the service API for WebSectionService service.
// Fields should be assigned to their respective handler implementations only before
// RegisterWebSectionServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type WebSectionServiceService struct {
	GetWebSectionPage func(context.Context, *GetWebSectionPageRequest) (*GetWebSectionPageResponse, error)
}

func (s *WebSectionServiceService) getWebSectionPage(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	if s.GetWebSectionPage == nil {
		return nil, status.Errorf(codes.Unimplemented, "method GetWebSectionPage not implemented")
	}
	in := new(GetWebSectionPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.GetWebSectionPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/stroeer.web.section.v1.WebSectionService/GetWebSectionPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetWebSectionPage(ctx, req.(*GetWebSectionPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterWebSectionServiceService registers a service implementation with a gRPC server.
func RegisterWebSectionServiceService(s grpc.ServiceRegistrar, srv *WebSectionServiceService) {
	sd := grpc.ServiceDesc{
		ServiceName: "stroeer.web.section.v1.WebSectionService",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "GetWebSectionPage",
				Handler:    srv.getWebSectionPage,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "stroeer/web/section/v1/web_section_service.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewWebSectionServiceService creates a new WebSectionServiceService containing the
// implemented methods of the WebSectionService service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewWebSectionServiceService(s interface{}) *WebSectionServiceService {
	ns := &WebSectionServiceService{}
	if h, ok := s.(interface {
		GetWebSectionPage(context.Context, *GetWebSectionPageRequest) (*GetWebSectionPageResponse, error)
	}); ok {
		ns.GetWebSectionPage = h.GetWebSectionPage
	}
	return ns
}

// UnstableWebSectionServiceService is the service API for WebSectionService service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableWebSectionServiceService interface {
	GetWebSectionPage(context.Context, *GetWebSectionPageRequest) (*GetWebSectionPageResponse, error)
}
