// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleServiceClient interface {
	// Returns a core article by it's id
	GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*Article, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

var articleServiceGetArticleStreamDesc = &grpc.StreamDesc{
	StreamName: "GetArticle",
}

func (c *articleServiceClient) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*Article, error) {
	out := new(Article)
	err := c.cc.Invoke(ctx, "/stroeer.core.v1.ArticleService/GetArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceService is the service API for ArticleService service.
// Fields should be assigned to their respective handler implementations only before
// RegisterArticleServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type ArticleServiceService struct {
	// Returns a core article by it's id
	GetArticle func(context.Context, *GetArticleRequest) (*Article, error)
}

func (s *ArticleServiceService) getArticle(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/stroeer.core.v1.ArticleService/GetArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetArticle(ctx, req.(*GetArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterArticleServiceService registers a service implementation with a gRPC server.
func RegisterArticleServiceService(s grpc.ServiceRegistrar, srv *ArticleServiceService) {
	srvCopy := *srv
	if srvCopy.GetArticle == nil {
		srvCopy.GetArticle = func(context.Context, *GetArticleRequest) (*Article, error) {
			return nil, status.Errorf(codes.Unimplemented, "method GetArticle not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "stroeer.core.v1.ArticleService",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "GetArticle",
				Handler:    srvCopy.getArticle,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "stroeer/core/v1/core_article_service.proto",
	}

	s.RegisterService(&sd, nil)
}
