// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package article

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArticlePageServiceClient is the client API for ArticlePageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticlePageServiceClient interface {
	//*
	//############################################################################
	//# Description
	//############################################################################
	//Returns the requested article with all render relevant data for the user and SEO bots.
	//
	//############################################################################
	//# Status/Error scenario's
	//############################################################################
	//
	//scenario: found
	//description: article was found in the datastore and is published according to it's metadata
	//gRPC status: OK
	//gRPC error payload: none
	//HTTP status: OK
	//cacheable: yes
	//
	//scenario: invalid id
	//description: article id is invalid
	//gRPC status: INVALID_ARGUMENT
	//gRPC error payload: google.rpc.BadRequest
	//HTTP status: 400
	//cacheable: yes
	//
	//scenario: not found
	//description: article was not found in the datastore
	//gRPC status: NOT_FOUND
	//gRPC error payload: google.rpc.ResourceInfo
	//HTTP status: 404
	//cacheable: yes
	//
	//scenario: not published yet
	//description: article was found in the datastore but according to it's metadata the article is not published yet
	//gRPC status: NOT_FOUND
	//gRPC error payload: google.rpc.ResourceInfo with info about the 'start_time'
	//HTTP status: 404
	//cacheable: yes
	//
	//scenario: expired
	//description: article was found in the datastore but is expired according to it's metadata
	//gRPC status: NOT_FOUND
	//gRPC error payload: google.rpc.ResourceInfo with info about the 'end_time'
	//HTTP status: 404
	//cacheable: yes
	//
	//scenario: deleted/archived
	//description: article was found in the datastore but it's state is marked as deleted/archived
	//gRPC status: FAILED_PRECONDITION
	//gRPC error payload: google.rpc.PreconditionFailure with info about the state
	//HTTP status: 410
	//cacheable: yes
	//
	//scenario: internal
	//description: internal error processing the article
	//gRPC status: INTERNAL
	//gRPC error payload: none
	//HTTP status: 500
	//cacheable: no
	//
	//scenario: timeout
	//description: timeout loading and processing the article
	//gRPC status: DEADLINE_EXCEEDED
	//gRPC error payload: none
	//HTTP status: 504
	//cacheable: no
	//
	//*Redirect cases should be defined after requirements are clear**
	GetArticlePage(ctx context.Context, in *GetArticlePageRequest, opts ...grpc.CallOption) (*GetArticlePageResponse, error)
}

type articlePageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticlePageServiceClient(cc grpc.ClientConnInterface) ArticlePageServiceClient {
	return &articlePageServiceClient{cc}
}

func (c *articlePageServiceClient) GetArticlePage(ctx context.Context, in *GetArticlePageRequest, opts ...grpc.CallOption) (*GetArticlePageResponse, error) {
	out := new(GetArticlePageResponse)
	err := c.cc.Invoke(ctx, "/stroeer.page.article.v1.ArticlePageService/GetArticlePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticlePageServiceServer is the server API for ArticlePageService service.
// All implementations must embed UnimplementedArticlePageServiceServer
// for forward compatibility
type ArticlePageServiceServer interface {
	//*
	//############################################################################
	//# Description
	//############################################################################
	//Returns the requested article with all render relevant data for the user and SEO bots.
	//
	//############################################################################
	//# Status/Error scenario's
	//############################################################################
	//
	//scenario: found
	//description: article was found in the datastore and is published according to it's metadata
	//gRPC status: OK
	//gRPC error payload: none
	//HTTP status: OK
	//cacheable: yes
	//
	//scenario: invalid id
	//description: article id is invalid
	//gRPC status: INVALID_ARGUMENT
	//gRPC error payload: google.rpc.BadRequest
	//HTTP status: 400
	//cacheable: yes
	//
	//scenario: not found
	//description: article was not found in the datastore
	//gRPC status: NOT_FOUND
	//gRPC error payload: google.rpc.ResourceInfo
	//HTTP status: 404
	//cacheable: yes
	//
	//scenario: not published yet
	//description: article was found in the datastore but according to it's metadata the article is not published yet
	//gRPC status: NOT_FOUND
	//gRPC error payload: google.rpc.ResourceInfo with info about the 'start_time'
	//HTTP status: 404
	//cacheable: yes
	//
	//scenario: expired
	//description: article was found in the datastore but is expired according to it's metadata
	//gRPC status: NOT_FOUND
	//gRPC error payload: google.rpc.ResourceInfo with info about the 'end_time'
	//HTTP status: 404
	//cacheable: yes
	//
	//scenario: deleted/archived
	//description: article was found in the datastore but it's state is marked as deleted/archived
	//gRPC status: FAILED_PRECONDITION
	//gRPC error payload: google.rpc.PreconditionFailure with info about the state
	//HTTP status: 410
	//cacheable: yes
	//
	//scenario: internal
	//description: internal error processing the article
	//gRPC status: INTERNAL
	//gRPC error payload: none
	//HTTP status: 500
	//cacheable: no
	//
	//scenario: timeout
	//description: timeout loading and processing the article
	//gRPC status: DEADLINE_EXCEEDED
	//gRPC error payload: none
	//HTTP status: 504
	//cacheable: no
	//
	//*Redirect cases should be defined after requirements are clear**
	GetArticlePage(context.Context, *GetArticlePageRequest) (*GetArticlePageResponse, error)
	mustEmbedUnimplementedArticlePageServiceServer()
}

// UnimplementedArticlePageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedArticlePageServiceServer struct {
}

func (UnimplementedArticlePageServiceServer) GetArticlePage(context.Context, *GetArticlePageRequest) (*GetArticlePageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticlePage not implemented")
}
func (UnimplementedArticlePageServiceServer) mustEmbedUnimplementedArticlePageServiceServer() {}

// UnsafeArticlePageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticlePageServiceServer will
// result in compilation errors.
type UnsafeArticlePageServiceServer interface {
	mustEmbedUnimplementedArticlePageServiceServer()
}

func RegisterArticlePageServiceServer(s grpc.ServiceRegistrar, srv ArticlePageServiceServer) {
	s.RegisterService(&ArticlePageService_ServiceDesc, srv)
}

func _ArticlePageService_GetArticlePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticlePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticlePageServiceServer).GetArticlePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stroeer.page.article.v1.ArticlePageService/GetArticlePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticlePageServiceServer).GetArticlePage(ctx, req.(*GetArticlePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticlePageService_ServiceDesc is the grpc.ServiceDesc for ArticlePageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticlePageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stroeer.page.article.v1.ArticlePageService",
	HandlerType: (*ArticlePageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticlePage",
			Handler:    _ArticlePageService_GetArticlePage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stroeer/page/article/v1/article_page_service.proto",
}
