// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package section

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SectionServiceClient is the client API for SectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SectionServiceClient interface {
	GetSectionPage(ctx context.Context, in *GetSectionPageRequest, opts ...grpc.CallOption) (*GetSectionPageResponse, error)
}

type sectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSectionServiceClient(cc grpc.ClientConnInterface) SectionServiceClient {
	return &sectionServiceClient{cc}
}

var sectionServiceGetSectionPageStreamDesc = &grpc.StreamDesc{
	StreamName: "GetSectionPage",
}

func (c *sectionServiceClient) GetSectionPage(ctx context.Context, in *GetSectionPageRequest, opts ...grpc.CallOption) (*GetSectionPageResponse, error) {
	out := new(GetSectionPageResponse)
	err := c.cc.Invoke(ctx, "/stroeer.pages.section.v1.SectionService/GetSectionPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SectionServiceService is the service API for SectionService service.
// Fields should be assigned to their respective handler implementations only before
// RegisterSectionServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type SectionServiceService struct {
	GetSectionPage func(context.Context, *GetSectionPageRequest) (*GetSectionPageResponse, error)
}

func (s *SectionServiceService) getSectionPage(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	if s.GetSectionPage == nil {
		return nil, status.Errorf(codes.Unimplemented, "method GetSectionPage not implemented")
	}
	in := new(GetSectionPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.GetSectionPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/stroeer.pages.section.v1.SectionService/GetSectionPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetSectionPage(ctx, req.(*GetSectionPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterSectionServiceService registers a service implementation with a gRPC server.
func RegisterSectionServiceService(s grpc.ServiceRegistrar, srv *SectionServiceService) {
	sd := grpc.ServiceDesc{
		ServiceName: "stroeer.pages.section.v1.SectionService",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "GetSectionPage",
				Handler:    srv.getSectionPage,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "stroeer/pages/section/v1/web_section_service.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewSectionServiceService creates a new SectionServiceService containing the
// implemented methods of the SectionService service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewSectionServiceService(s interface{}) *SectionServiceService {
	ns := &SectionServiceService{}
	if h, ok := s.(interface {
		GetSectionPage(context.Context, *GetSectionPageRequest) (*GetSectionPageResponse, error)
	}); ok {
		ns.GetSectionPage = h.GetSectionPage
	}
	return ns
}

// UnstableSectionServiceService is the service API for SectionService service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableSectionServiceService interface {
	GetSectionPage(context.Context, *GetSectionPageRequest) (*GetSectionPageResponse, error)
}
