name: wiki-docs-generator

on:
  release:
    types: [published, edited]

jobs:
  docs:
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      RELEASE_SPEC_FOLDER: api-docs/${{ github.event.release.tag_name }}
      SPEC_FILE_NAME: api-spec.md
    steps:
      - uses: actions/checkout@v2
      - name: Gen docs
        run: make
      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
      - name: add docs to api-spec.md
        run: |
          cd tapir.wiki
          [ -d $SPEC_FOLDER ] || mkdir -p $SPEC_FOLDER
          yes | cp -r ../$SPEC_FOLDER .
          echo "• [$RELEASE_TAG]($RELEASE_SPEC_FOLDER/$SPEC_FILE_NAME)" >> ../../api-spec.md
          cd ..
      - name: push changed docs to wiki
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "update wiki api-specs" && git push