name: proto

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  buf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          setup_only: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          breaking_against: "https://github.com/stroeer/tapir.git#branch=main"

      - name: generate
        run: make generate
