name: proto

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main


jobs:
  buf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          setup_only: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          breaking_against: "https://github.com/stroeer/tapir.git#branch=main"

      - name: generate
        run: make generate

  node:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      # we need Node for the local execution of protoc Typescript plugin
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: 'node/package-lock.json'
          node-version-file: 'node/.nvmrc'
          registry-url: "https://npm.pkg.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.BUF_TOKEN }}

      # we need Node for the local execution of protoc Typescript plugin
      - name: install
        working-directory: node
        run: npm ci

      - name: generate
        run: make generate TEMPLATE=buf.gen.node.yaml

      - name: checks
        working-directory: node
        run: npm run checks

      - name: publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        working-directory: node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG=${GITHUB_REF/refs\/tags\/v/}
          echo $RELEASE_TAG
          npm version $RELEASE_TAG
          npm publish

  node-buf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: 'node-buf/package-lock.json'
          node-version-file: 'node-buf/.nvmrc'
          registry-url: "https://npm.pkg.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.BUF_TOKEN }}

      - name: generate
        run: make generate TEMPLATE=buf.gen.node-buf.yaml

      - name: install
        working-directory: node-buf
        run: npm ci

      - name: publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        working-directory: node-buf
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG=${GITHUB_REF/refs\/tags\/v/}
          echo $RELEASE_TAG
          npm version $RELEASE_TAG
          npm publish
